name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # Job de Build (já deve existir ou ser similar)
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Eleventy site
      run: npm run build

    - name: Upload artifact (opcional, mas recomendado para depuração)
      uses: actions/upload-artifact@v4
      with:
        name: _site
        path: _site

  # Se você tiver um job separado para reportar o status do build, adicione-o aqui.
  # Caso contrário, ignore este job e remova-o da lista 'needs' abaixo.
  report-build-status:
    runs-on: ubuntu-latest
    needs: build # Este job depende do job 'build'
    steps:
    - name: Report status (exemplo)
      run: echo "Build concluído com sucesso!"

  # Job de Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [build, report-build-status] # <--- AQUI ESTÁ A MUDANÇA PRINCIPAL
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact (se você usou upload-artifact no job de build)
      uses: actions/download-artifact@v4
      with:
        name: _site
        path: _site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        # Se o seu repositório for um User/Organization Page (ex: username.github.io),
        # você pode precisar da branch 'master' em vez de 'gh-pages'.
        # publish_branch: master
